version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # - package-ecosystem: pip
  #   directory: /docker/segment-anything
  #   schedule:
  #     interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /gui
    schedule:
      interval: daily
