version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # only allow dependencies those are direcly described in the docs/requirements.txt file
  # to prevent generating redundant PRs for the same dependency update.
  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily
    allow:
      - dependency-name: "opencv-python-headless"
      - dependency-name: "*sphinx*"
      - dependency-name: "jupyte*"
      - dependency-name: "markupsafe"
      - dependency-name: "nbconvert"
      - dependency-name: "ipython"
      - dependency-name: "myst-parser"
      - dependency-name: "tensorflow"
      - dependency-name: "pandoc"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: daily
