config:
  list-item-indent: space
  no-dead-urls: false
  # MD013/line-length - Line length
  MD013:
    # Number of characters
    line_length: 100
    # Number of characters for headings
    heading_line_length: 120
  strong-marker: "*"
  emphasis-marker: "_"
  unordered-list-marker-style: "-"
  ordered-list-marker-style: "."
  no-file-name-irregular-characters: false
  list-item-spacing: false

globs:
  - '**/*.md'
  - '!tests/*.md'