config:
  # MD013/line-length - Line length
  MD013:
    # Number of characters
    line_length: 100
    # Number of characters for headings
    heading_line_length: 120
  MD022: false
  MD024: false
  MD032: false

globs:
  - '**/*.md'
  - '!tests/*.md'