# Default state for all rules
default: true

# line-length - Line length
MD013: false
  # # Number of characters
  # line_length: 100
  # # Number of characters for headings
  # heading_line_length: 120

# blanks-around-headings/blanks-around-headers - Headings should be surrounded by blank lines
MD022: false

# no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024: false

# blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: false

# blanks-around-lists - Lists should be surrounded by blank lines
MD032: false

# no-inline-html - Inline HTML
MD033: false

# no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false

# fenced-code-language: Fenced code blocks should have a language
MD040: false

# first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# link-fragments - Link fragments should be valid
MD051: false