FROM openvino/model_server:2023.0-gpu@sha256:c29fa4c2c7bd0432f85e69fd2ed28bff9c3e27defaf0055b3c9b314df21a9d38 AS ovms

USER root

RUN mkdir -p /models/sam_encoder/1
RUN mkdir -p /models/sam_decoder/1

COPY --from=onnx-exporter /ws/output/encoder/* /models/sam_encoder/1/
COPY --from=onnx-exporter /ws/output/decoder/* /models/sam_decoder/1/

ADD ovms/model_config_list.json /models/model_config_list.json

USER ovms

ENTRYPOINT ["/ovms/bin/ovms", "--config_path", "/models/model_config_list.json"]
