FROM nvcr.io/nvidia/tritonserver:23.07-py3@sha256:643b13be1086195615554646cf1d6c0ba2273349f175bfab833142534af1796d AS nvidia-triton

ADD triton/sam_encoder /models/sam_encoder
ADD triton/sam_decoder /models/sam_decoder

RUN mkdir -p /models/sam_encoder/1
RUN mkdir -p /models/sam_decoder/1

COPY --from=onnx-exporter /ws/output/encoder/* /models/sam_encoder/1/
COPY --from=onnx-exporter /ws/output/decoder/* /models/sam_decoder/1/

ENTRYPOINT [ "tritonserver", "--model-repository=/models" ]
