name: "sam_decoder"
backend: "onnxruntime"
input [
    {
        name: "image_embeddings"
        data_type: TYPE_FP32
        dims: [ 1, 256, 64, 64 ]
    }
]
input [
    {
        name: "point_coords"
        data_type: TYPE_FP32
        dims: [ 1, -1, 2 ]
    }
]
input [
    {
        name: "point_labels"
        data_type: TYPE_FP32
        dims: [ 1, -1 ]
    }
]
input [
    {
        name: "mask_input"
        data_type: TYPE_FP32
        dims: [ 1, 1, 256, 256 ]
    }
]
input [
    {
        name: "has_mask_input"
        data_type: TYPE_FP32
        dims: [ 1 ]
    }
]
input [
    {
        name: "orig_im_size"
        data_type: TYPE_FP32
        dims: [ 2 ]
    }
]
output [
    {
        name: "masks"
        data_type: TYPE_FP32
        dims: [ -1, -1, -1, -1 ]
    }
]
output [
    {
        name: "iou_predictions"
        data_type: TYPE_FP32
        dims: [ -1, 1 ]
    }
]
output [
    {
        name: "low_res_masks"
        data_type: TYPE_FP32
        dims: [ -1, 1, -1, -1 ]
    }
]
