name: Build and upload to PyPI

on:
  workflow_dispatch: # run on request (no need for PR)
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-2022']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-wheels_${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build sdist
        run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist_${{ matrix.os }}
          path: dist/*.tar.gz

  publish_package:
    name: Publish package
    needs: [build_wheels, build_sdist]
    environment: pypi
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: artifact-*
        merge-multiple: true
    # to determine where to publish the source distribution to PyPI or TestPyPI
    - name: Check tag
      id: check-tag
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ github.ref }}
        regex: '^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?$'
    - name: Upload package distributions to github
      if: ${{ steps.check-tag.outputs.match != '' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Publish package distributions to PyPI
      if: ${{ steps.check-tag.outputs.match != '' }}
      uses: pypa/gh-action-pypi-publish@v1.10.3
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish package distributions to TestPyPI
      if: ${{ steps.check-tag.outputs.match == '' }}
      uses: pypa/gh-action-pypi-publish@v1.10.3
      with:
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true
