name: Security Scans

on:
  schedule:
    # Run security checks every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - release**
  merge_group:
    branches:
      - develop
      - release**
  push:
    branches:
      - develop
      - release**

permissions: {}

jobs:
  zizmor-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - &harden_runner
        name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          disable-sudo: true
          disable-telemetry: true
          egress-policy: block
          allowed-endpoints: >
            # Azure Wire Server IP
            168.63.129.16:80
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            releases.astral.sh:443
            semgrep.dev:443

      - &checkout
        name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Zizmor scan
        uses: open-edge-platform/geti-ci/actions/zizmor@cffbec1b3b7c155efa789cd2ea67a2a765a4369f # zizmor/v0.1.4
        with:
          severity-level: "LOW"
          confidence-level: "LOW"
          scan-scope: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'changed' || 'all' }}
          fail-on-findings: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'true' || 'false' }}

  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - *harden_runner
      - *checkout

      - name: Run Bandit scan
        uses: open-edge-platform/geti-ci/actions/bandit@134a7e6b1658ea9eb97b7f52f724ed88a2878ea7 # bandit/v0.1.2
        with:
          severity-level: "LOW"
          confidence-level: "LOW"
          config_file: "pyproject.toml"
          scan-scope: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'changed' || 'all' }}
          fail-on-findings: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'true' || 'false' }}

  trivy-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - *harden_runner
      - *checkout

      - name: Run Trivy scan
        id: trivy
        uses: open-edge-platform/geti-ci/actions/trivy@940b10164d8c2a6a6e4d786fe1c0aeab74bd629d
        with:
          scan_type: "fs"
          scan-scope: all
          severity: LOW
          scanners: "secret,config"
          format: "sarif"
          timeout: "15m"
          ignore_unfixed: "false"

  semgrep-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - *harden_runner

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run Semgrep scan
        id: semgrep
        uses: open-edge-platform/geti-ci/actions/semgrep@940b10164d8c2a6a6e4d786fe1c0aeab74bd629d
        with:
          severity: "LOW"
          scan-scope: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'changed' || 'all' }}
          fail-on-findings: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'true' || 'false' }}
